name: prbuild
on:
  pull_request:
    branches:
    - master
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
    - name: sdk checkout
      uses: actions/checkout@v2
    - name: sdk deps
      run: go get -v -t -d ./...
    - name: sdk test
      env:
        INTEGRATION_TESTS: yes
      run: go test -mod readonly -v ./...
    - name: tests checkout
      uses: actions/checkout@v2
      with:
        repository: unistack-org/micro-tests
        ref: refs/heads/master
        path: micro-tests
        fetch-depth: 1
    - name: tests deps
      run: |
        cd micro-tests
        go mod edit -replace="github.com/unistack-org/micro/v3=../"
        go get -v -t -d ./...
    - name: tests test
      env:
        INTEGRATION_TESTS: yes
      run: cd micro-tests && go test -mod readonly -v ./...
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: lint
        uses: golangci/golangci-lint-action@v2
        continue-on-error: true
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.30
          # Optional: working directory, useful for monorepos
          # working-directory: somedir
          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
